import product1 from './assets/img1.webp';
import product2 from './assets/img2.jpg';
import product3 from './assets/img3.webp';
import product4 from './assets/img4.jpg';
import product5 from './assets/img5.webp';
import product6 from './assets/img6.jpg';
import product7 from './assets/img7.webp';
import product8 from './assets/img8.webp';

export const PRODUCTS = [
    {
        id: 1,
        productName: "Playstation 5",
        price: 449.99,
        productImage: product1,
        condition: "New",
        description: "Brand new, unopened and undamaged. The box has some rips and creases.", 
        seller: "coolguy123",
        sellerId: 1,
        aboutSeller: "I offer affordable electronics backed by a 100% satisfaction guarantee mentality and a 60-day return policy.",
        comment1: "Could have been packaged a bit better in shipping but works , no issues. Good quality and happy I purchased.",
        comment2: "The console looks good. But I didn't get a controller. I'm not sure if it was supposed to come with one. But it's a little disappointing",
        stock: 1,
        q1: "Is it easy to set up and use?",
        q2: "Can this console play physical discs?",
        a1: "The console comes with easy-to-follow instructions for setup.",
        a2: "Yes, it can play physical discs.",
    },
    {
        id: 2,
        productName: "Apple Watch Series 5 (GPS 40MM)",
        price: 146.75,
        productImage: product2,
        condition: "Used",
        description: "It's used and has some scratches. Only comes with the watch and band, does not include a charging cable or power brick.", 
        seller: "johnjohn1",
        sellerId: 2,
        aboutSeller: "I sell second-hand products of high quality. If you have any questions please contact me anytime.",
        comment1: "I bought this to keep track of my heart rate and it has been so useful in many more ways than I intended!",
        comment2: "Great product, but buyers BEWARE! Buy directly from Apple and NOT Amazon. Made the mistake of buying from here, but ended up receiving a defective watch.",
        stock: 0,
        q1: "How is this watch's battery life?",
        q2: "How does the watch track sleep quality?",
        a1: "It has all-day battery life and can last 18 hours on a single charge.",
        a2: "The watch uses sensors to track heart rate and blood oxygen to measure sleep quality.",
    },
    {
        id: 3,
        productName: "Sony DualSense Wireless Controller",
        price: 31.54,
        productImage: product3,
        condition: "Parts Only",
        description: "Both sticks on the controller don't work, it's for parts only.", 
        seller: "isellstuff",
        sellerId: 3,
        aboutSeller: "Selling parts and As-Is devices.",
        comment1: "No complaints overall.", 
        comment2: "I recieved this controller less than a week ago and the finish on it is coming off as if it was painted over.",
        stock: 3,
        q1: "What parts of this controller are non-functional?",
        q2: "Is the controller fixable?",
        a1: "The sticks of the controller do not work.",
        a2: "Yes, as long as you replace the sticks.",
    },
    {
        id: 4,
        productName: "Restored Nintendo DSi",
        price: 139.99,
        productImage: product4,
        condition: "Refurbished",
        description: "Refurbished, the outer shell has some wear and tear. The language is Japanese and can't be switched to English. It is region locked and can only play software released in Japan.", 
        seller: "jimmyjohn",
        sellerId: 4,
        aboutSeller: "I sell 90% gaming related products.",
        comment1: "This is great, everything works and its 100% original, only problem is that the system was not exactly in excellent condition, the back has some scuffs, same with the front.",
        comment2: "Complete junk. Won't charge and won't stay on. Big waste of money",
        stock: 2,
        q1: "What is the average battery life?",
        q2: "How durable is this console?",
        a1: "The battery lasts 9-14 hours on a single charge.",
        a2: "The console is in good shape and is decently durable.",
    },
    {
        id: 5,
        productName: "Logitech MX Mechanical Wireless Keyboard",
        price: 349.99,
        productImage: product5,
        condition: "New",
        description: "Brand new, never opened. Comes with Logi Bolt receiver, USB-C charging cable, and user documentation.", 
        seller: "jane234",
        sellerId: 5,
        aboutSeller: "I sell consumer electronics, accessories, and parts.",
        comment1: "Works as it should, comfortable to use. Shipped as expected.",
        comment2: "Mine must be unplugged and replugged back in after every restart for it to work. No idea why.",
        stock: 0,
        q1: "How does it connect to devices?",
        q2: "What is the keyboard's language?",
        a1: "This keyboard connects to devices wirelessly via bluetooth.",
        a2: "This keyboard has a QWERTY layout.",
    },
    {
        id: 6,
        productName: "Sanpyl RX 580 Gaming Graphics Card 8GB GDDR5",
        price: 104.35,
        productImage: product6,
        condition: "Used",
        description: "Used in good condition, has light coil whine.", 
        seller: "ilovehcishop",
        sellerId: 6,
        aboutSeller: "Buy pre-owned and save big. Our prices and expert service cannot be beat.",
        comment1: "It runs great and so far has handled every game I have thrown at it on ultra high. Runs pretty cool under load.",
        comment2: "This GPU is very noisy and overheats easily.",
        stock: 1,
        q1: "Is its performance good for gaming?",
        q2: "What is the maximum resolution supported?",
        a1: "Yes, this graphics card offers excellent gaming performance.",
        a2: "This graphics card supports 4K resolution at 60Hz.",
    },
    {
        id: 7,
        productName: "Apple AirPods Pro (2nd Generation)",
        price: 129.99,
        productImage: product7,
        condition: "New",
        description: "They are brand new and unopened. Includes the earbuds, charging case, and a lightning charging cable.", 
        seller: "bestseller12345",
        sellerId: 7,
        aboutSeller: "My shop stocks Apple items!",
        comment1: "I like this particular design as it allows me to still hear my surroundings. I use them to listen to my computer while I play music on my stereo in the background.",
        comment2: "It does not sit comfortably in my ear. Since it doesn't sit well in my ears the noise cancellation really doesn't work all that well where there is a significant difference in the background noise.",
        stock: 4,
        q1: "What's the battery life like on these?",
        q2: "What is the bluetooth range?",
        a1: "The battery lasts up to 24 hours with the charging case.",
        a2: "It can maintain a connection up to 30 feet away from their device.",
    },
    {
        id: 8,
        productName: "Nintendo Switch OLED Console Black",
        price: 87.43,
        productImage: product8,
        condition: "Parts Only",
        description: "The switch has been damaged by water but has been dried out and put back together. The screen does not work but the switch turns on and works normally when docked.", 
        seller: "nintendoseller",
        sellerId: 8,
        aboutSeller: "Supply your technology needs through brand new or like new computers, tablets, consoles, toys, and accessories!",
        comment1: "The best console ever! This toy is great for on the go or at home!",
        comment2: "I got the package and it was all bubble wrapped. I understood that it was for parts but I expected someone to inspect it before sending it as it had greasy stains and smudge prints all over the screen.",
        stock: 1,
        q1: "Does it have expandable storage capacity?",
        q2: "What is the battery life like compared to previous models?",
        a1: "Yes, it has 64 GB of internal storage and can use microSD cards up to 2 TB for additional storage.",
        a2: "The battery can last up to 9 hours which is similar to the original Switch model.",
    },
];